# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample the Factor Loading Curves
#'
#' @param BtY (J x T) matrix B.t()*Y for basis matrix B
#' @param Beta (T x K) matrix of factors
#' @param Psi (J x K) matrix of previous factor loading curve coefficients
#' @param BtB (J x J) matrix of B.t()*B
#' @param Omega (J x J) prior precision/penalty matrix
#' @param lamda K-dimensional vector of prior precisions
#' @param sigmat2 T-dimensional vector of time-dependent observation error variances
#' @useDynLib FDLM
#' @import Rcpp
#' @export
sampleFLC <- function(BtY, Beta, Psi, BtB, Omega, lambda, sigmat2) {
    .Call('FDLM_sampleFLC', PACKAGE = 'FDLM', BtY, Beta, Psi, BtB, Omega, lambda, sigmat2)
}

#' Sample the Factor Loading Curves, For the special case in which BtB = diag(J)
#'
#' @param BtY (J x T) matrix B.t()*Y for basis matrix B
#' @param Beta (T x K) matrix of factors
#' @param Psi (J x K) matrix of previous factor loading curve coefficients
#' @param Omega (J x J) prior precision/penalty matrix
#' @param lamda K-dimensional vector of prior precisions
#' @param sigmat2 T-dim vector of time-dependent observation error variances
#' @export
sampleFLC_orthog <- function(BtY, Beta, Psi, Omega, lambda, sigmat2) {
    .Call('FDLM_sampleFLC_orthog', PACKAGE = 'FDLM', BtY, Beta, Psi, Omega, lambda, sigmat2)
}

