# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Factor Loading Curve Sampling Algorithm
#'
#' Sample the factor loading curve basis coefficients subject to
#' an orthonormality constraint.
#'
#' @param BtY \code{J x T} matrix \code{B.t()*Y} for basis matrix B
#' @param Beta \code{T x K} matrix of factors
#' @param Psi \code{J x K} matrix of previous factor loading curve coefficients
#' @param BtB \code{J x J} matrix of \code{B.t()*B}
#' @param Omega \code{J x J} prior precision/penalty matrix
#' @param lamda \code{K}-dimensional vector of prior precisions
#' @param sigmat2 \code{T}-dimensional vector of time-dependent observation error variances
#' @return Psi \code{J x K} matrix of (orthogonal) factor loading curve coefficients
#'
#' @note This function uses \code{Rcpp} for computational efficiency.
#'
#' @useDynLib FDLM
#' @import Rcpp
#' @export
sampleFLC <- function(BtY, Beta, Psi, BtB, Omega, lambda, sigmat2) {
    .Call('FDLM_sampleFLC', PACKAGE = 'FDLM', BtY, Beta, Psi, BtB, Omega, lambda, sigmat2)
}

#' Factor Loading Curve Sampling Algorithm
#'
#' Sample the factor loading curve basis coefficients subject to
#' an orthonormality constraint for the special case in which \code{BtB = diag(J)}.
#'
#' @param BtY \code{J x T} matrix \code{B.t()*Y} for basis matrix B
#' @param Beta \code{T x K} matrix of factors
#' @param Psi \code{J x K} matrix of previous factor loading curve coefficients
#' @param Omega \code{J x J} prior precision/penalty matrix
#' @param lamda \code{K}-dimensional vector of prior precisions
#' @param sigmat2 \code{T}-dimensional vector of time-dependent observation error variances
#' @return Psi \code{J x K} matrix of (orthogonal) factor loading curve coefficients
#'
#' @note This function uses \code{Rcpp} for computational efficiency.
#'
#' @useDynLib FDLM
#' @import Rcpp
#' @export
sampleFLC_orthog <- function(BtY, Beta, Psi, Omega, lambda, sigmat2) {
    .Call('FDLM_sampleFLC_orthog', PACKAGE = 'FDLM', BtY, Beta, Psi, Omega, lambda, sigmat2)
}

